#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
    arr=s.split(' ')
    res=''
    for i in arr:
        res+=i.capitalize()+' '
    return res
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
    
Input:
hello  world lol
Output:
Hello  World Lol
